FROM dunglas/frankenphp:1-php8.3-bookworm

# Install PostgreSQL extension untuk PHP
RUN install-php-extensions pdo_pgsql

WORKDIR /app

# Salin seluruh project SaCine
COPY . .

# Gunakan konfigurasi Caddy
COPY Caddyfile /etc/caddy/Caddyfile

# Jalankan FrankenPHP
CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]